<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-1T2AMDB" name="TestCases.Home_Contactus_PageVerification_001" tests="6" failures="1" timestamp="2021-01-17T21:35:40 IST" time="22.598" errors="0">
  <testcase name="verifyContactUseLink" time="8.511" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- verifyContactUseLink -->
  <testcase name="verifyContactUseLink" time="5.492" classname="TestCases.Home_Contactus_PageVerification_001">
    <failure type="java.lang.AssertionError" message="expected [CUSTOMER SERVICE - CONTACT US ] but found [CUSTOMER SERVICE - CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CUSTOMER SERVICE - CONTACT US ] but found [CUSTOMER SERVICE - CONTACT US]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.Home_Contactus_PageVerification_001.verifyContactUseLink(Home_Contactus_PageVerification_001.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyContactUseLink -->
  <testcase name="verifyContactUseLink" time="8.595" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- verifyContactUseLink -->
  <testcase name="sendMessage_UploadusingSendKeys" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- sendMessage_UploadusingSendKeys -->
  <testcase name="Monster_FileUploadUsingRobotClass" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- Monster_FileUploadUsingRobotClass -->
  <testcase name="homeButtonVerification" classname="TestCases.Home_Contactus_PageVerification_001">
    <skipped/>
  </testcase> <!-- homeButtonVerification -->
</testsuite> <!-- TestCases.Home_Contactus_PageVerification_001 -->
